// src/features/claim-roi/config/vaultConfig.ts

export const VAULT_CONFIG: Record<string, { 
  price: number;
  tokenAddress: string;
  usdcAddress: string;
  enabled: boolean;
}> = {
  "CAS56N75A3KYYON72ELM65FVEOV36VGLTQAOFQJIRYN7HM4L2H6TFOWD": {
    price: 50,   // +50% ROI
    tokenAddress: "CBW4W4GEGD5MNXCUHGOAJ64IXLFHDMDDD65ITVM3HVIYSK22PGSHIJ5N",
    usdcAddress: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
    enabled: true,
  },

  "CCAPAJY44JOBHJAWVZCGAWAMK4XCST4EIZENZWI6DQHPD4RGYBKM6H7D": {
    price: 20,
    tokenAddress: "CBFTQZ3NATN6Y7PKYWGCF7OH6JOFTWUMYAJQDCBPSKGPWWQ7N23RTSNK",
    usdcAddress: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
    enabled: true,
  },

  "CC7RJ4EACM5HMYKIMYJ5OPYDOYING7AAHE5ACHZK3F7QSXIMIWRU5GFC": {
    price: 35,
    tokenAddress: "CBW4W4GEGD5MNXCUHGOAJ64IXLFHDMDDD65ITVM3HVIYSK22PGSHIJ5N",
    usdcAddress: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
    enabled: false, // example disabled vault
  },
};
